### PR TITLE
Extend Pairing logic on discovery and add debug lib

### PR DESCRIPTION
**Pull request by Apollon77**
* add debug lib
  * add communication logging
  * add tlv parsing logging
* move PairingFeatureFlags to Discovery classes because definition different per protocol
* add some convenient names to ble service definition to have same fields for "config version" ("c#") and "device id" ("id") for both service types
* add availableForPairing to service object and adjust the examples
* add getPairingMethod methods to the Client classes (as async for both because for BLE needs to be read from device while in Discovery response for IP devices, also adjust examples - so still not really "automatically resolved" but as method for the user to call and provide response to the pair method
* smaller adjustments in docs and  errors

### CODE REVIEW

**Comment by Apollon77** [comment]
@mrstegeman because i'm not at home right now I could not test that at all, but it would be great if you could already have a review look over it when you find time if the changes are basically ok for you ...
I will test once back at home in a week - I then should also have an IP and an BLE device available for real testing of it.

**Comment by mrstegeman** [comment]
@Apollon77 I really don't have time to work on this library anymore. Given that you've put more work into it than anybody else, would you be interested in taking over maintenance of this library? I'd be happy to transfer it to you, that way it can continue to grow and be used by other projects.

**Comment by Apollon77** [comment]
I would be happy to take over because I have some stuff planned for it. My name on npm is apollon77 too. Thank you for transfer

**Comment by Apollon77** [comment]
PS: But if you have an opinion on the PR I would also be happy to hear it :-)

**Comment by mrstegeman** [comment]
You'll need to delete your fork before I can transfer the repo to you. Let me know when you've done that.

**Comment by Apollon77** [comment]
ok, Then lets please merge this PR - the my fork is current ... else I get chaos

**Comment by Apollon77** [comment]
@mrstegeman fork deleted

**Pull request merged**
